### ISSUE TITLE
find does not transform the partitionKey back

### ISSUE THREAD

**Issue by obiwabrakenobi** [typedorm/typedorm#184] opened 2021-12-03 08:50 UTC
I have a model defined like this

```typescript
class BaseEvent {
    @Attribute()
    id!: string;
    @Attribute()
    sortKey!: number;
}

@Entity({
    name: 'SpecificEvent',
    primaryKey: {
        partitionKey: 'SpecificEvent___{{id}}',
        sortKey: {
            alias: 'sortKey',
        } as unknown as string,
    },
})
export class SpecificEvent extends BaseEvent {
    @Attribute()
    value!: number;
}

// connection
export const getConnection = (
    tableName: string,
    documentClient?: DocumentClient
) => {
    return createConnection({
        table: new Table({
            name: tableName,
            partitionKey: 'id',
            sortKey: 'sortKey',
        }),
        entities: [SpecificEvent],
        documentClient,
        name: v4(),
    });
};
```

Im storing some events via Batch in dynamo db and the partitionKey gets transformed into `SpecificEvent___xxx`. But when I now try to load the items with `find` or `findOne` I still receive in the loaded entity with id as the full string `SpecificEvent___xxx` rather than `xxx`. Am I missing something here?

Loading is done via:

```typescript
const result = await this.entityManager.find(
    SpecificEvent,
    {
        id: conditionId,
    },
    {
        limit: limit,
        orderBy: QUERY_ORDER.DESC,
    }
);
```

Also in the debug log I see that there is no transformation applied.

Here is the log from the transformation

```
2021-12-03T09:14:35.005Z typedorm:transform:log 42a35974-8625-4de7-8131-e4db99b074a4 RESPONSE ConditionAlertEventDTO Before: 
Body:  
{
  "sortKey": 1622529932772,
  "__en": "SpecificEvent",
  "id": "SpecificEvent___100ConditionId",
  "value": 6.831363201141357
}


2021-12-03T09:14:35.006Z typedorm:transform:log 42a35974-8625-4de7-8131-e4db99b074a4 RESPONSE ConditionAlertEventDTO After: 
Body:  
{
  "sortKey": 1622529932772,
  "id": "SpecificEvent___100ConditionId", // this should have been "id": "100ConditionId"
  "value": 6.831363201141357
}
```

**Comment by whimzyLive** [comment] 2021-12-05 12:54
Hey @obiwabrakenobi,

I had a look at the issues you suggested were happening, but I can't replicate them. 
Can you please provide the logs of the batch write operation? Looks like the `id` you are expecting to have the transformation applied for, isn't in the correct format in the first place.

Please Have a look at https://github.com/typedorm/typedorm/pull/185/files and let me know what is different in your case. 

Thanks

**Comment by obiwabrakenobi** [comment] 2021-12-06 08:22
I might have found the issue. I'm creating the table with 

```typescript
export const getConnection = (
    tableName: string,
    documentClient?: DocumentClient
) => {
    return createConnection({
        table: new Table({
            name: tableName,
            partitionKey: 'id',
            sortKey: 'sortKey',
        }),
        entities: [SpecificEvent],
        documentClient,
        name: v4(),
    });
};
```

but the keys do reflect properties of the entity. I investigated your PR and saw that the `testTable` in your tests is created like 

```typescript
export const testTable = new Table({
  name: 'test-table',
  partitionKey: 'PK',
  sortKey: 'SK',
  indexes: {
    GSI1: {
      type: INDEX_TYPE.GSI,
      partitionKey: 'GSI1PK',
      sortKey: 'GSI1SK',
    },
    LSI1: {
      type: INDEX_TYPE.LSI,
      sortKey: 'LSI1SK',
    },
  },
});
```` 

After I changed the provided example to 

```tyescript
export const getConnection = (
    tableName: string,
    documentClient?: DocumentClient
) => {
    return createConnection({
        table: new Table({
            name: tableName,
            partitionKey: 'PK',
            sortKey: 'SK',
        }),
        entities: [SpecificEvent],
        documentClient,
        name: v4(),
    });
};
```
it worked like expected. There might be an issue when a table is created with _partitionKey_ and _sortKey_ with identifiers from the entity!?

**Comment by whimzyLive** [comment] 2021-12-06 14:04
@obiwabrakenobi 
Aaha, I see the issue now.

The issue is what is defined as partition key/sort key. 
Since you have a partition key set to 'id' and the entity also has an attribute called 'id', The TypeDORM decides to not parse the 'id' property( because it is a part of the partition key)

This is the desired behaviour, but I think it should throw an error when an entity has an overlapping attribute name to prevent such accidents as this one.

**Comment by whimzyLive** [comment] 2021-12-06 14:31
closing this in favor of https://github.com/typedorm/typedorm/issues/186.

**Closed by whimzyLive** 2021-12-06 14:31 UTC
Labels: under investigation
